"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { categories, defaultProducts, type Product } from "@/lib/catalog";
import "./catalog.css";

type CartItem = { key:string; productId:string; name:string; image:string; price:number; quantity:number; size?:string; color?:string };
const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});

function Brand(){return <a className="brand" href="#inicio" aria-label="Ir al inicio de MAVI Personalizados"><Image className="official-logo" src="/brand/mavi-personalizados-logo.png" alt="MAVI Personalizados" width={768} height={768} priority/></a>}

export default function Home(){
 const [products,setProducts]=useState<Product[]>(defaultProducts);
 const [query,setQuery]=useState("");
 const [category,setCategory]=useState("Todos");
 const [menuOpen,setMenuOpen]=useState(false);
 const [selected,setSelected]=useState<Product|null>(null);
 const [selectedSize,setSelectedSize]=useState("");
 const [selectedColor,setSelectedColor]=useState("");
 const [quantity,setQuantity]=useState(1);
 const [cart,setCart]=useState<CartItem[]>([]);
 const [cartOpen,setCartOpen]=useState(false);
 const [checkoutOpen,setCheckoutOpen]=useState(false);
 const [orderNumber,setOrderNumber]=useState("");
 const [ready,setReady]=useState(false);

 useEffect(()=>{let active=true;Promise.resolve().then(()=>{try{const saved=localStorage.getItem("mavi-cart");if(saved&&active)setCart(JSON.parse(saved))}catch{}if(active)setReady(true)});fetch("/api/products",{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject()).then(data=>{if(active)setProducts(data)}).catch(()=>{});return()=>{active=false}},[]);
 useEffect(()=>{if(ready)localStorage.setItem("mavi-cart",JSON.stringify(cart))},[cart,ready]);

 const visible=useMemo(()=>products.filter(product=>(category==="Todos"||product.category===category)&&(`${product.name} ${product.category} ${product.description}`).toLowerCase().includes(query.trim().toLowerCase())),[category,query,products]);
 const itemCount=cart.reduce((sum,item)=>sum+item.quantity,0);
 const subtotal=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);

 function openProduct(product:Product){setSelected(product);setSelectedSize(product.sizes?.[0]??"");setSelectedColor(product.colors?.[0]??"");setQuantity(1)}
 function addProduct(product:Product,qty=1,size="",color=""){
  const key=`${product.id}-${size}-${color}`;
  setCart(current=>{const existing=current.find(item=>item.key===key);if(existing)return current.map(item=>item.key===key?{...item,quantity:item.quantity+qty}:item);return[...current,{key,productId:product.id,name:product.name,image:product.image,price:product.price,quantity:qty,size:size||undefined,color:color||undefined}]});
  setSelected(null);setCartOpen(true);
 }
 function changeQuantity(key:string,next:number){if(next<=0)setCart(current=>current.filter(item=>item.key!==key));else setCart(current=>current.map(item=>item.key===key?{...item,quantity:next}:item))}
 function finishOrder(event:FormEvent<HTMLFormElement>){event.preventDefault();setOrderNumber(`MAVI-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`);setCart([])}

 return <main id="inicio">
  <div className="top-strip"><span>Diseños hechos especialmente para ti</span><span>Santiago · Envíos a todo Chile</span></div>
  <header className="store-header"><Brand/><label className="search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="¿Qué producto buscas?" aria-label="Buscar productos"/>{query&&<button onClick={()=>setQuery("")} aria-label="Limpiar búsqueda">×</button>}</label><button className="cart-button" onClick={()=>setCartOpen(true)} aria-label={`Abrir carro, ${itemCount} productos`}><span className="bag-icon">▱</span><span><small>Tu carro</small><strong>{itemCount} {itemCount===1?"producto":"productos"}</strong></span>{itemCount>0&&<b>{itemCount}</b>}</button></header>
  <nav className="store-nav"><div className="category-menu"><button className="category-trigger" onClick={()=>setMenuOpen(!menuOpen)} aria-expanded={menuOpen}><span>☰</span> PRODUCTOS <b>⌄</b></button>{menuOpen&&<div className="category-dropdown">{products.map(product=><button key={product.id} onClick={()=>openProduct(product)}><Image src={product.image} alt="" width={44} height={44}/><span>{product.shortName}</span><b>›</b></button>)}</div>}</div><div className="nav-links"><a href="#inicio">Inicio</a><a href="#productos">Tienda</a><a href="#como-comprar">Cómo comprar</a><a href="#contacto">Contacto</a></div><a className="nav-cta" href="#productos">Comprar ahora</a></nav>

  <section className="shop-hero"><div className="hero-copy"><p className="eyebrow">CREADO PARA TI</p><h1>Tu idea.<br/><em>Tu estilo.</em></h1><p>Productos personalizados para regalar, celebrar o darle identidad a tu emprendimiento.</p><a className="primary" href="#productos">Explorar productos <span>→</span></a><div className="hero-points"><span>✓ Atención personalizada</span><span>✓ Envíos a todo Chile</span></div></div><div className="hero-showcase">{[products.find(item=>item.id==="polera")??products[0],products.find(item=>item.id==="taza")??products[1],products.find(item=>item.id==="topper")??products[2]].filter(Boolean).map((product,index)=><button key={product.id} className={index===0?"hero-main":""} onClick={()=>openProduct(product)}><Image src={product.image} alt={product.name} width={index===0?900:700} height={index===0?900:700} priority={index===0}/><span><b>{index===0?"Poleras personalizadas":index===1?"Regalos únicos":"Momentos especiales"}</b><small>{index===1?`Desde ${money.format(product.price)}`:"Ver producto →"}</small></span></button>)}</div></section>

  <section className="service-strip"><article><span>✦</span><div><b>Personalizado por MAVI</b><small>Diseños preparados con dedicación.</small></div></article><article><span>⌁</span><div><b>Despacho flexible</b><small>Retiro, Santiago y regiones.</small></div></article><article><span>✓</span><div><b>Compra acompañada</b><small>Confirmamos cada detalle antes de producir.</small></div></article></section>

  <section className="category-section"><div className="section-heading"><div><p className="eyebrow">ENCUENTRA TU FAVORITO</p><h2>Compra por producto</h2></div><a href="#productos">Ver toda la tienda →</a></div><div className="category-tiles">{products.map(product=><button key={product.id} onClick={()=>openProduct(product)}><Image src={product.image} alt={product.name} width={520} height={520}/><span>{product.shortName}</span></button>)}</div></section>

  <section id="productos" className="product-section"><div className="section-heading"><div><p className="eyebrow">TIENDA MAVI</p><h2>Productos personalizados</h2></div><p>{visible.length} resultados</p></div><div className="filter-row">{categories.map(item=><button key={item} className={category===item?"active":""} onClick={()=>setCategory(item)}>{item}</button>)}</div>{visible.length?<div className="shop-grid">{visible.map(product=><article className="shop-card" key={product.id}>{product.tag&&<span className="product-tag">{product.tag}</span>}<button className="product-image" onClick={()=>openProduct(product)}><Image src={product.image} alt={product.name} width={800} height={800}/><span>Ver detalles</span></button><div className="product-info"><small>{product.category}</small><h3>{product.name}</h3><p>{product.description}</p><div className="price-line"><div><span>Desde</span><strong>{money.format(product.price)}</strong></div><button onClick={()=>product.sizes||product.colors?openProduct(product):addProduct(product)} aria-label={`Agregar ${product.name} al carro`}>+</button></div></div></article>)}</div>:<div className="no-results"><b>No encontramos productos con esa búsqueda.</b><button onClick={()=>{setQuery("");setCategory("Todos")}}>Ver todos</button></div>}<p className="price-note">Valores referenciales para esta primera versión. Confirmaremos el precio final según cantidad, material y diseño antes de producir.</p></section>

  <section className="occasion-banner"><div><p className="eyebrow">EMPRESAS · EVENTOS · REGALOS</p><h2>Haz que tu idea se convierta en algo inolvidable.</h2><p>Preparamos pedidos individuales y por volumen, con alternativas pensadas para cada ocasión.</p><a className="primary coral" href="#productos">Ver productos</a></div><div className="occasion-collage"><Image src="/products/delantal.png" alt="Delantal parrillero" width={560} height={560}/><Image src="/products/gorra.png" alt="Gorra personalizada" width={560} height={560}/><Image src="/products/chapitas.png" alt="Chapitas personalizadas" width={560} height={560}/></div></section>

  <section id="como-comprar" className="buy-steps"><div className="section-heading centered"><div><p className="eyebrow">ASÍ DE SIMPLE</p><h2>Compra en tres pasos</h2></div></div><div><article><span>01</span><h3>Elige</h3><p>Selecciona tu producto, opciones y cantidad.</p></article><article><span>02</span><h3>Confirma</h3><p>Completa tus datos y selecciona el tipo de entrega.</p></article><article><span>03</span><h3>Coordinamos</h3><p>Revisamos tu pedido y te enviamos los datos de transferencia.</p></article></div></section>

  <footer id="contacto"><div className="footer-brand"><Brand/><p>Productos personalizados para expresar, regalar y celebrar.</p></div><div><h3>Tienda</h3>{products.slice(0,6).map(product=><button key={product.id} onClick={()=>openProduct(product)}>{product.shortName}</button>)}</div><div><h3>Ayuda</h3><a href="#como-comprar">Cómo comprar</a><button onClick={()=>setCartOpen(true)}>Ver mi carro</button><a href="#productos">Productos</a><a href="/admin">Administrar</a></div><div><h3>MAVI Personalizados</h3><span>Santiago, Chile</span><span>Envíos a todo Chile</span><small>Los datos de contacto se incorporarán antes del lanzamiento.</small></div></footer><div className="copyright">© 2026 MAVI Personalizados</div>

  {selected&&<div className="overlay" onMouseDown={()=>setSelected(null)}><section className="product-modal" onMouseDown={event=>event.stopPropagation()} role="dialog" aria-modal="true" aria-label={selected.name}><button className="close" onClick={()=>setSelected(null)} aria-label="Cerrar">×</button><div className="modal-gallery"><Image src={selected.image} alt={selected.name} width={900} height={900}/><div><button className="active"><Image src={selected.image} alt="Vista principal" width={160} height={160}/></button><button><Image src={selected.image} alt="Vista de detalle" width={160} height={160}/></button></div></div><div className="modal-copy"><p className="eyebrow">{selected.category}</p><h2>{selected.name}</h2><p>{selected.description}</p><div className="modal-price"><span>Desde</span><strong>{money.format(selected.price)}</strong></div>{selected.sizes&&<fieldset><legend>Talla</legend><div className="option-row">{selected.sizes.map(size=><button type="button" key={size} className={selectedSize===size?"active":""} onClick={()=>setSelectedSize(size)}>{size}</button>)}</div></fieldset>}{selected.colors&&<fieldset><legend>Color</legend><select value={selectedColor} onChange={event=>setSelectedColor(event.target.value)}>{selected.colors.map(color=><option key={color}>{color}</option>)}</select></fieldset>}<div className="purchase-row"><div className="quantity"><button onClick={()=>setQuantity(Math.max(1,quantity-1))}>−</button><span>{quantity}</span><button onClick={()=>setQuantity(quantity+1)}>+</button></div><button className="primary" onClick={()=>addProduct(selected,quantity,selectedSize,selectedColor)}>Agregar al carro</button></div><small className="availability">La disponibilidad y el diseño se confirman antes de la producción.</small></div></section></div>}

  {cartOpen&&<div className="drawer-overlay" onMouseDown={()=>setCartOpen(false)}><aside className="cart-drawer" onMouseDown={event=>event.stopPropagation()} aria-label="Carro de compra"><div className="drawer-head"><div><small>TU COMPRA</small><h2>Carro <span>({itemCount})</span></h2></div><button onClick={()=>setCartOpen(false)} aria-label="Cerrar carro">×</button></div>{cart.length?<><div className="cart-items">{cart.map(item=><article key={item.key}><Image src={item.image} alt={item.name} width={130} height={130}/><div><h3>{item.name}</h3>{(item.size||item.color)&&<small>{[item.size&&`Talla ${item.size}`,item.color].filter(Boolean).join(" · ")}</small>}<strong>{money.format(item.price)}</strong><div className="mini-quantity"><button onClick={()=>changeQuantity(item.key,item.quantity-1)}>−</button><span>{item.quantity}</span><button onClick={()=>changeQuantity(item.key,item.quantity+1)}>+</button><button className="remove" onClick={()=>changeQuantity(item.key,0)}>Eliminar</button></div></div></article>)}</div><div className="drawer-summary"><div><span>Subtotal</span><strong>{money.format(subtotal)}</strong></div><small>El despacho se cotiza según la dirección.</small><button className="primary" onClick={()=>{setCartOpen(false);setCheckoutOpen(true)}}>Continuar pedido</button><button className="keep-buying" onClick={()=>setCartOpen(false)}>Seguir comprando</button></div></>:<div className="empty-cart"><span>▱</span><h3>Tu carro está vacío</h3><p>Encuentra un producto especial y agrégalo aquí.</p><button className="primary" onClick={()=>setCartOpen(false)}>Ver productos</button></div>}</aside></div>}

  {checkoutOpen&&<div className="overlay checkout-overlay"><section className="checkout-modal" role="dialog" aria-modal="true" aria-label="Finalizar pedido"><button className="close" onClick={()=>{setCheckoutOpen(false);setOrderNumber("")}} aria-label="Cerrar">×</button>{orderNumber?<div className="order-success"><span>✓</span><p className="eyebrow">PEDIDO RECIBIDO</p><h2>¡Gracias por elegir MAVI!</h2><p>Tu número de pedido es <strong>{orderNumber}</strong>. Nos comunicaremos contigo para confirmar diseño, disponibilidad, despacho y datos de transferencia.</p><button className="primary" onClick={()=>{setCheckoutOpen(false);setOrderNumber("")}}>Volver a la tienda</button></div>:<form onSubmit={finishOrder}><div className="checkout-form"><p className="eyebrow">FINALIZAR COMPRA</p><h2>Datos del pedido</h2><div className="form-grid"><label>Nombre completo<input required name="name" placeholder="Tu nombre"/></label><label>Teléfono o WhatsApp<input required name="phone" type="tel" placeholder="+56 9..."/></label><label className="full">Correo electrónico<input required name="email" type="email" placeholder="nombre@correo.cl"/></label></div><fieldset><legend>Forma de entrega</legend><label className="radio"><input required type="radio" name="delivery" value="retiro" defaultChecked/><span><b>Retiro coordinado</b><small>Te informaremos el lugar y horario.</small></span></label><label className="radio"><input type="radio" name="delivery" value="santiago"/><span><b>Despacho en Santiago</b><small>Tarifa según comuna.</small></span></label><label className="radio"><input type="radio" name="delivery" value="regiones"/><span><b>Envío a regiones</b><small>Por empresa de transporte.</small></span></label></fieldset><label>Comentarios del pedido<textarea name="notes" rows={3} placeholder="Cuéntanos cualquier detalle importante"/></label></div><aside className="checkout-summary"><h3>Resumen</h3>{cart.map(item=><div className="checkout-item" key={item.key}><span>{item.quantity} × {item.name}</span><strong>{money.format(item.price*item.quantity)}</strong></div>)}<div className="checkout-total"><span>Subtotal</span><strong>{money.format(subtotal)}</strong></div><div className="transfer-box"><b>Pago por transferencia</b><p>Te enviaremos los datos bancarios después de revisar y confirmar tu pedido.</p></div><button className="primary" type="submit">Confirmar pedido</button><small>No se realizará ningún cobro en esta etapa.</small></aside></form>}</section></div>}
 </main>
}
